spring.application.name=gym-backend
spring.datasource.url=jdbc:mysql://localhost:3306/gymdb
spring.datasource.username=fathak
spring.datasource.password=Fathak20#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true